plugins:
  topic_gallery_enabled:
    default: true
    client: false
  topic_gallery_allowed_groups:
    type: group_list
    list_type: compact
    default: "1" # admin group
    allow_any: false
    refresh: true
  topic_gallery_minimum_image_size:
    default: 64
    min: 0
    max: 1000
  topic_gallery_excluded_categories:
    type: category_list
    default: ""
    client: true
  topic_gallery_post_menu_button:
    default: true
    client: true
  topic_gallery_show_author:
    default: true
    client: true
  topic_gallery_show_post_date:
    default: true
    client: true
  topic_gallery_show_topic_title:
    default: true
    client: true
  topic_gallery_topic_title_links_to_post:
    default: false
    client: true
  topic_gallery_show_category:
    default: true
    client: true
  topic_gallery_show_post_link:
    default: true
    client: true
  topic_gallery_show_image_details:
    default: true
    client: true
  topic_gallery_category_include_subcategories:
    default: true
